@{

RootModule = 'Posh-ACME.psm1'
ModuleVersion = '4.8.0'
GUID = '5f52d490-68dd-411c-8252-828c199a4e63'
Author = 'Ryan Bolger'
Copyright = '(c) 2018 Ryan Bolger. All rights reserved.'
Description = 'ACME protocol client for obtaining certificates using Let''s Encrypt (or other ACME compliant CA)'
CompatiblePSEditions = @('Desktop','Core')
PowerShellVersion = '5.1'
DotNetFrameworkVersion = '4.7.1'

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
    'lib\BC.Crypto.1.8.8.2-netstandard2.0.dll'
    'System.Net.Http'
)

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Posh-ACME.Format.ps1xml'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Complete-PAOrder'
    'Export-PAAccountKey'
    'Get-KeyAuthorization'
    'Get-PAAccount'
    'Get-PAAuthorization'
    'Get-PACertificate'
    'Get-PAOrder'
    'Get-PAPlugin'
    'Get-PAPluginArgs'
    'Get-PAServer'
    'Install-PACertificate'
    'Invoke-HttpChallengeListener'
    'New-PAAccount'
    'New-PACertificate'
    'New-PAOrder'
    'New-PAAuthorization'
    'Publish-Challenge'
    'Remove-PAAccount'
    'Remove-PAOrder'
    'Remove-PAServer'
    'Revoke-PAAuthorization'
    'Revoke-PACertificate'
    'Save-Challenge'
    'Send-ChallengeAck'
    'Set-PAAccount'
    'Set-PAOrder'
    'Set-PAServer'
    'Submit-ChallengeValidation'
    'Submit-OrderFinalize'
    'Submit-Renewal'
    'Unpublish-Challenge'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'Get-PAAuthorizations'
)

PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'LetsEncrypt','ssl','tls','certificates','acme','Linux','Mac'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/rmbolger/Posh-ACME/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/rmbolger/Posh-ACME'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## 4.8.0 (2021-09-09)

* Documentation Revamp
  * https://poshac.me/docs is a new dedicated website for Posh-ACME documentation. Existing guides and tutorials have been migrated there from the Github wiki. The site is currently generated using the Markdown files in the `docs` folder in the main project repository by [MkDocs](https://www.mkdocs.org/). So it should now be easier to contribute fixes and updates.
  * The native module help is now also generated by [platyPS](https://github.com/PowerShell/platyPS) from the Markdown files in `docs/Functions`.
  * `Get-Help <function name> -Online` should now open your browser to the appropriate page on the documentation site.
* The DeSEC plugin has new `DSCToken` and `DSCTTL` params to avoid conflicts with the DNSimple plugin. The old `DSToken`, `DSTokenInsecure`, and `DSTTL` parameters have been deprecated.
* "Insecure" plugin parameter sets which include secrets, tokens, or passwords using a standard String instead of a SecureString or PSCredential have been deprecated across all plugins that had them.
  * Deprecated means that they will continue to work in Posh-ACME 4.x, but will stop working when 5.0 is released.
  * If you are currently using a deprecated parameter set, please migrate to a secure one when convenient.
  * See your plugin's [usage guide](https://poshac.me/docs/v4/Plugins/) for more information.
  * For help finding deprecated parameters in your config, see [this guide](https://poshac.me/docs/v4/Guides/Find-Deprecated-PluginArgs/)
* The following plugins have added new "Secure" parameter sets:
  * BlueCat
  * Cloudflare
  * DOcean
  * Dreamhost
  * Dynu
  * EasyDNS
  * GoDaddy
  * NameCom
  * Zonomi
* A `Plugin` property has been added to the output objects returned by `Get-PAPlugin <Plugin> -Params`
'@

    }

}

}
